FROM python:3.6

# get arguments
ARG DQM_CONFIG

# install resources
RUN apt-get update && apt-get install -y nginx
WORKDIR /var/www/flask-vue-template/flask_app
COPY /requirements.txt requirements.txt
RUN pip install -r ./requirements.txt

# set up config files
RUN rm -r /root/.cache
COPY /config/nginx.conf /etc/nginx/
COPY /config/flask-site-nginx.conf /etc/nginx/conf.d
COPY /config/uwsgi.ini /etc/uwsgi/
COPY /config/supervisord.conf /etc/supervisord.conf

# add user
RUN groupadd nginx
RUN useradd -g nginx nginx

# set environment variables
ENV PYTHONPATH=$PYTHONPATH:`pwd`

EXPOSE 8080 8106

# run
CMD ["python", "run.py"]
